# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageimage',
            name='image_name',
        ),
        migrations.AddField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(default='', upload_to=b'', verbose_name='page_images'),
            preserve_default=False,
        ),
    ]
