# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161020_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(upload_to='page_images/'),
        ),
    ]
