# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20161020_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='teaser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('local_destination', 'local_destination'), ('regional_destination', 'regional_destination'), ('housing', 'housing'), ('shopping', 'shopping'), ('medical', 'medical'), ('transportation', 'transportation'), ('education', 'education')], default='restaurant', max_length=50),
        ),
    ]
