# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20161121_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
