# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161028_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username2',
            field=models.CharField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
