# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentView',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('body', models.TextField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('user_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'microfeed_comment_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('body', models.TextField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
                ('user_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'microfeed_post_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('body', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('body', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microfeed.Post'),
        ),
    ]
