# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfeed', '0002_auto_20161003_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
