# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microfeed', '0004_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image_path',
            new_name='image_name',
        ),
    ]
